
services:
  db:
    image: mysql:8.0
    container_name: messaging_db
    restart: always
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQLDB: ${MYSQL_DATABASE}
      MYSQLUSER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build:
      context: .
    container_name: messaging_web
    command: python3 manage.py runserver 0.0.0.0:8000
    env_file: .env
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - "8000:8000"

volumes:
  db_data:
